### ISSUE TITLE
FindCelero.cmake or CeleroConfig.cmake

### ISSUE THREAD

**Issue by erikzenker** [DigitalInBlue/Celero#98]
Is there a FindCeleron.cmake or CeleronConfig.cmake available for an easy integration into other projects ?

**Comment by DigitalInBlue** [comment]
There is not.  The code would be something like:

```
set(CELERO_DIRECTORY ${celeroDirectoryDefault} CACHE PATH "")
set(CELERO_INCLUDE_DIR ${CELERO_DIRECTORY}/include CACHE PATH "Celero's include directory.")
set(CELERO_LIBRARY celero CACHE STRING "")

#If celero is "out of tree", we have to add the subdirectory differently.
add_subdirectory(${CELERO_DIRECTORY} ${CMAKE_CURRENT_BINARY_DIR}/celero)
```

**Comment by mloskot** [comment]
Alternatively, use `ExternalProject_Add`. Here is how I managed to do it in order to automate clone-build-link workflow for my benchmark  https://github.com/mloskot/string_benchmark/

It works locally as well as in CI builds.

**Comment by mloskot** [comment]
FYI, Celero 2.4 is also available from Conan packages

```
conan remote add ppodsiadly https://api.bintray.com/conan/ppodsiadly/conan
conan install celero/2.4.0@ppodsiadly/stable
```

**Comment by DigitalInBlue** [comment]
See ```celero\cmake\FindCelero.cmake```

**Comment by weirdo-neutrino** [comment]
Here are my thoughts about installation.

### CMake documentation

[It is said](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html) that "Packages provide dependency information to CMake based buildsystems". In turn "CMake provides direct support for two forms of packages, [Config-file Packages](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#id1) and [Find-module Packages](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#find-module-packages)". Also "Indirect support for `pkg-config` packages is also provided via the [FindPkgConfig](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html#module:FindPkgConfig) module".

### Solutions

This gives 4 possible solution for upstreams:

1. documentation
2. pkg-config
3. FindModule
4. config-file

### Choice

1. Documenting the exact place where targets are put is not CMake way. And not a good way in any way. In worse case downstreams have to read code where it is done.
2. CMake can interoparate with pkg-config in both directions, though it's a little bit clunky. In presence of better options this one is not considered.
3. CMake [states](https://cmake.org/cmake/help/latest/manual/cmake-packages.7.html#find-module-packages) about the third one that "Typically, a find module is needed when the upstream is not built with CMake, or is not CMake-aware enough to otherwise provide a package configuration file".
4. So ideally we are left with the forth.

### Config-file way

This solution won't require FindModule file at all as all necessary information will be generated by CMake on installation. This will change the directory where `celero-target.cmake` is stored and add `celero-config.cmake`.

I can pull-request this variant with or without the minimum information about CMake config-file concept so you can make a code review.

**Comment by DigitalInBlue** [comment]
I agree the CMake configuration here is long in the tooth.  I am happy to accept a pull request to modernize it!  I simply haven't had time to do it.  Thank you for your time and effort!
